name: fetch_data_dio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get: ^4.6.5
  lottie: ^1.4.1
  internet_connection_checker: ^0.0.1+4
  top_snackbar_flutter: ^2.1.1
  scrollable_positioned_list: ^0.3.2
  font_awesome_flutter: ^10.1.0
  file_picker: ^5.2.1
  open_app_settings: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  image_path: "assets/logo/ic_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
